FROM gomicro/goose

ARG DB_NAME
ARG DB_ADDR
ARG DB_USER
ARG DB_PASSWORD

ADD ./migrations/*.sql /migrations
ADD ./scripts/dev/docker/entrypoint.sh /migrations

RUN ["chmod", "+x", "/migrations/entrypoint.sh"]

CMD ["bash", "/migrations/entrypoint.sh"]