FROM golang:1.24

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY ../../../go.mod ../../../go.sum ./
RUN go mod download

COPY ../../../ .

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /job ./cmd/job/main.go

# Run
CMD ["/job"]